services:
  database:
    container_name: "database"
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE=docuroom_db'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_PASSWORD=user@12345'
      - 'MYSQL_USER=devuser'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    container_name: "backend"
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - MYSQL_DATABASE_URL=jdbc:mysql://database:3306/docuroom_db?useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_DATABASE_USERNAME=devuser
      - MYSQL_DATABASE_PASSWORD=user@12345

  frontend:
    container_name: "frontend"
    build: ../frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    expose:
      - "3000"
volumes:
  mysql_data:
