server:
  port: 8080

logging:
  level:
    org.springframework.security: trace
  pattern.console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
spring:
  application:
    name: "backend"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: ${MYSQL_DATABASE_URL:jdbc:mysql://localhost:3306/docuroom_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver




